export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const ORGCHANGE = 'ORGCHANGE';
export const LOADGLOBAL = 'LOADGLOBAL';
export const CHANGEAPP = 'CHANGEAPP';

export const ADDGUIDE = 'ADDGUIDE';

export const GETtracking = 'GETtracking';
export const SELECTTRACKING = 'SELECTTRACKING';
export const INFOSELECTTRACKING = 'INFOSELECTTRACKING';
export const MESSAGESFROMUSER = 'MESSAGESFROMUSER';
export const OPENMODALMESSAGE = 'OPENMODALMESSAGE';
export const SETMESSAGESELECTED = 'SETMESSAGESELECTED';
export const SENDMESSAGEOK = 'SENDMESSAGEOK';
export const SENDMESSAGEFAIL = 'SENDMESSAGEFAIL';


export const MANAGESNACKBAR = 'MANAGESNACKBAR';
export const MANAGEBACKDROP = 'MANAGEBACKDROP';
export const MANAGEQUESTION = 'MANAGEQUESTION';


export const REFRESHtracking = 'REFRESHtracking';

export const SETDATA = 'SETDATA';
export const SETDISTRICTS = 'SETDISTRICTS';
export const ITEMDISTRICTS = 'ITEMDISTRICTS';
export const SELECTMARKER = 'SELECTMARKER';
export const DESSELECTMARKER = 'DESSELECTMARKER';
export const ADDMARKERVISIBLE = 'ADDMARKERVISIBLE';
export const CHANGESTEP = 'CHANGESTEP';
export const VEHICLESELECTED = 'VEHICLESELECTED';
export const CLEANASSIGNED = 'CLEANASSIGNED';
export const SELECTGUIDE = 'SELECTGUIDE';
export const UPDATEATTEMPT = 'UPDATEATTEMPT';
export const DATAQUADRANT = 'DATAQUADRANT';
export const SELECTQUADRANT = 'SELECTQUADRANT';
export const QUADRANTGUIDES = 'QUADRANTGUIDES';
export const SELECTMARKERGLOBAL = 'SELECTMARKERGLOBAL';
export const SETOPENDRAWER = 'SETOPENDRAWER';
export const CHECKFILTERDISTRICT = 'CHECKFILTERDISTRICT';
export const LIGHTBOXCAROUSEL = 'LIGHTBOXCAROUSEL';


export const INFOSYS = 'INFOSYS';
export const REMOVEIMAGE = 'REMOVEIMAGE';